---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: springio/concourse-release-scripts
    tag: '0.3.4'
inputs:
- name: git-repo
- name: artifactory-repo
outputs:
- name: version
params:
  RELEASE_TYPE:
  ARTIFACTORY_SERVER:
  ARTIFACTORY_USERNAME:
  ARTIFACTORY_PASSWORD:
  SONATYPE_USER:
  SONATYPE_PASSWORD:
  SONATYPE_URL:
  SONATYPE_STAGING_PROFILE:
run:
  path: git-repo/ci/scripts/promote-version.sh
